# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ruZJlF5tFMRXMNFpMa-nUtpUFkTSmBm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import matplotlib.ticker as mtick

class SalesPipeline:
    def __init__(self):
        self.cities = ['Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Chennai', 'Pune']
        self.city_probs = [0.35, 0.15, 0.25, 0.10, 0.08, 0.07]

    def generate_and_process(self):
        start_date = datetime(2024, 4, 1)
        all_data = []
        for month_offset in range(23):
            current_month_start = start_date + timedelta(days=month_offset * 30.5)

            num_orders = int(800 * (1.03 ** month_offset))

            for _ in range(num_orders):
                order_day = current_month_start + timedelta(days=np.random.randint(0, 28))
                city = np.random.choice(self.cities, p=self.city_probs)
                base_price = np.random.randint(5000, 45000) * (1 + (month_offset * 0.012))
                if city in ['Mumbai', 'Bengaluru']: base_price *= 1.25

                all_data.append({
                    'order_date': order_day,
                    'city': city,
                    'unit_price': float(base_price),
                    'quantity': np.random.randint(1, 4)
                })
        return pd.DataFrame(all_data)

    def run_forecast(self, df):
        df['month_year'] = df['order_date'].dt.to_period('M').astype(str)
        monthly_rev = df.groupby('month_year')['total_revenue'].sum().sort_index()


        y = monthly_rev.values
        x = np.arange(len(y))
        slope, _ = np.polyfit(x, y, 1)


        last_val = y[-1]
        march_pred = last_val + slope
        april_pred = march_pred + slope

        next_months = ["2026-03", "2026-04"]
        future_preds = [march_pred, april_pred]


        plt.style.use('ggplot')
        fig, ax = plt.subplots(figsize=(13, 7), facecolor='white')


        ax.plot(monthly_rev.index, y, marker='o', color='#0077b6', linewidth=2, label='Actual Monthly Revenue')


        bridge_months = [monthly_rev.index[-1]] + next_months
        bridge_values = [last_val] + future_preds

        ax.plot(bridge_months, bridge_values, marker='D', color='#e63946',
                linestyle='--', linewidth=2.5, markersize=8, label='Q2 Target Projection')


        plt.xticks(monthly_rev.index[::3].tolist() + next_months)
        ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, p: f'₹{x/100000:.1f}L'))
        ax.set_title('Revenue Trajectory & Q2 Forecasting', fontsize=16, pad=20, fontweight='bold')
        ax.legend(loc='upper left')

        plt.tight_layout()
        plt.savefig('executive_forecast.png', dpi=300)
        plt.show()


pipeline = SalesPipeline()
df = pipeline.generate_and_process()
df['total_revenue'] = df['unit_price'] * df['quantity']
pipeline.run_forecast(df)